name: Run tests on PR for BEIAM

on:
  pull_request:
    branches: [ "main" ]


jobs:
  test-on-pr:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Run tests on PR
      run: mvn -B -U test --file ./beiam/pom.xml
